# coding=utf-8
# 重试时间间隔，单位ms
RETRY_INITIAL_INTERVAL_MILLS = 2000
# 最大等待时间，单位ms
CAPACITY = 10000
# 重试最大尝试次数
RETRY_MAX_ATTEMPTS = 6 * 3600 * 1000 / CAPACITY
LOGGER_NAME = "secretsmanagerCommonPlugin"

NOT_SUPPORT_TAMP_AK_TIMESTAMP = -1

MONITOR_AK_STATUS_ACTION = "monitorAkStatus"

SEND_BATCH_MESSAGE_ACTION = "sendBatchMessage"

UPDATE_CREDENTIAL_ACTION = "updateCredential"

RECOVERY_GET_SECRET_ACTION = "recoveryGetSecret"

# 默认令牌数
DEFAULT_MAX_TOKEN_NUMBER = 5

DEFAULT_RATE_LIMIT_PERIOD = 10 * 60 * 1000

DEFAULT_AUTOMATIC_ROTATION = "Enabled"

PROPERTY_NAME_KEY_ACCESS_KEY_ID = "AccessKeyId"

PROPERTY_NAME_KEY_ACCESS_KEY_SECRET = "AccessKeySecret"

PROPERTY_NAME_KEY_EXPIRE_TIMESTAMP = "ExpireTimestamp"

PROPERTY_NAME_KEY_GENERATE_TIMESTAMP = "GenerateTimestamp"

KMS_SECRET_CURRENT_STAGE_VERSION = "ACSCurrent"

PROPERTY_NAME_KEY_REFRESH_INTERVAL = "refreshInterval"

PROPERTY_NAME_KEY_SCHEDULE_ROTATE_TIMESTAMP = "scheduleRotateTimestamp"

DEFAULT_ROTATION_INTERVAL_IN_MS = 6 * 60 * 60 * 1000

DEFAULT_DELAY_INTERVAL = 5 * 60 * 1000

DEFAULT_RANDOM_DISTURBANCE_RANGE = 10 * 60 * 1000

PROPERTIES_MONITOR_PERIOD_MILLISECONDS_KEY = "monitor_period_milliseconds"

PROPERTIES_MONITOR_CUSTOMER_MILLISECONDS_KEY = "monitor_customer_milliseconds"

RAM_CREDENTIALS_SECRET_TYPE = "RAMCredentials"

EXTENDED_CONFIG_PROPERTY_SECRET_SUB_TYPE = "SecretSubType"

RAM_USER_ACCESS_KEY_SECRET_SUB_TYPE = "RamUserAccessKey"

CUSTOM_MESSAGE_ACTION = "customMessage"

DEFAULT_ROTATION_INTERVAL = "86400s"

DEFAULT_CREDENTIALS_CONFIG_NAME = "managed_credentials_providers.properties"
